shallow_clone: false

image: 
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - x64
  
configuration: 
  - Debug
  - Release

install:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - SET VS_ARCH=""
  - if "%platform%" == "x64" SET VS_ARCH=-A%PLATFORM%
  - echo VS_ARCH = %VS_ARCH%
  - cmake %VS_ARCH% .. > %APPVEYOR_BUILD_FOLDER%\configure.log
  - cmake --build . --config %CONFIGURATION% > %APPVEYOR_BUILD_FOLDER%\build.log
  - cd ..
  - mkdir %APPVEYOR_PROJECT_NAME%
  - if exist docs cp -r docs %APPVEYOR_PROJECT_NAME%
  - if exist examples cp -r examples %APPVEYOR_PROJECT_NAME%
  - if exist extensions cp -r extensions %APPVEYOR_PROJECT_NAME%
  - if exist externals cp -r externals %APPVEYOR_PROJECT_NAME%
  - if exist extras cp -r extras %APPVEYOR_PROJECT_NAME%
  - if exist help cp -r help %APPVEYOR_PROJECT_NAME%
  - if exist init cp -r init %APPVEYOR_PROJECT_NAME%
  - if exist java-classes cp -r java-classes %APPVEYOR_PROJECT_NAME%
  - if exist java-doc cp -r java-doc %APPVEYOR_PROJECT_NAME%
  - if exist jsui cp -r jsui %APPVEYOR_PROJECT_NAME%
  - if exist patchers cp -r patchers %APPVEYOR_PROJECT_NAME%
  - if exist tests cp -r tests %APPVEYOR_PROJECT_NAME%
  - cp icon.png %APPVEYOR_PROJECT_NAME%
  - cp License.md %APPVEYOR_PROJECT_NAME%
  - cp package-info.json %APPVEYOR_PROJECT_NAME%
  - cp ReadMe.md %APPVEYOR_PROJECT_NAME%
  - set SHORT_COMMIT=%APPVEYOR_REPO_COMMIT:~0,7%
  - 7z a %APPVEYOR_PROJECT_NAME%-win-%platform%-%SHORT_COMMIT%-%CONFIGURATION%.zip %APPVEYOR_PROJECT_NAME% > %APPVEYOR_BUILD_FOLDER%\archive.log

test_script:
  - cd build
  - ctest -C %CONFIGURATION% . -V > %APPVEYOR_BUILD_FOLDER%\test.log

artifacts:
  - name: Build
    path: '*.zip'
  - name: Log files
    path: '*.log'
    
on_failure:
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\configure.log
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\build.log
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\test.log

deploy:
  provider: S3
  access_key_id: AKIAJ4NHY5NBHT76DRGA
  secret_access_key:
    secure: 8v5xXOB5BONI4CoU5t08nkRyDMbV2TQKDvKBNrfFhHFVwHxa2v8l3FeoeWequCeT
  bucket: cycling74-ci-public
  folder: $(APPVEYOR_PROJECT_NAME)
  region: us-west-1
  set_public: true
  artifact: "$(APPVEYOR_PROJECT_NAME)-win-$(platform)-$(SHORT_COMMIT)-$(CONFIGURATION).zip"
