name: build & test
on:
  push:
      branches:
      - master
      - dev
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
        config:
          - Debug
          - Release

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
      - if: contains(matrix.os, 'windows')
        name: Install ffmpeg via vcpkg
        run: |
          cp .\vcpkg-helper\x64-windows-static-rel.cmake .\vcpkg\triplets\
          .\vcpkg\vcpkg.exe install ffmpeg[avformat,avdevice,avcode,core]:x64-windows-static-rel
      - if: contains(matrix.os, 'macos')
        name: Install ffmpeg via vcpkg(macos)
        run: |
          cp ./vcpkg-helper/x64-macos-rel.cmake ./vcpkg/triplets/
          brew upgrade
          brew install yasm
          ./vcpkg/vcpkg install ffmpeg[avformat,avdevice,avcode,core]:x64-macos-rel
      - name: configure project
        run: cmake -B build -DCMAKE_BUILD_CONFIG=${{ matrix.config }} .
      - name: build
        run: cmake --build build --config ${{ matrix.config }}
      - uses: papeloto/action-zip@v1
        with:
          files: .
          dest: rtpsendreceive-${{matrix.os}}.zip
      - uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: rtpsendreceive-${{matrix.os}}
          path: ${{github.workspace}}/rtpsendreceive-${{matrix.os}}.zip
      # - name: test
      #   run: cd build && ctest --build-config ${{ matrix.config }}
